# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_time', models.DateTimeField(auto_now_add=True)),
                ('direction', models.TextField()),
                ('dir_tag', models.CharField(blank=True, max_length=20, null=True)),
                ('arr_time', models.DateTimeField(blank=True, null=True)),
                ('arr_sec', models.IntegerField(blank=True, null=True)),
                ('is_depart', models.NullBooleanField()),
                ('layover', models.NullBooleanField()),
                ('vehic', models.CharField(blank=True, max_length=4, null=True)),
                ('trip', models.CharField(blank=True, max_length=8, null=True)),
                ('block', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(default='MBTA', max_length=4)),
                ('route_title', models.CharField(blank=True, max_length=20, null=True)),
                ('route_tag', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_title', models.TextField(blank=True, null=True)),
                ('stop_tag', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='prediction',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Route'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Stop'),
        ),
    ]
