# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='dinner',
            name='e_mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emood', to='eatout.Mood'),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='t_mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmood', to='eatout.Mood'),
        ),
    ]
