# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatout', '0002_auto_20171104_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
